drush,ccsm and private updates

diff --git a/bash/_drush_bashrc b/bash/_drush_bashrc
--- a/bash/_drush_bashrc
+++ b/bash/_drush_bashrc
@@ -7,9 +7,20 @@ alias den='drush -y pm-enable'
 alias ddi='drush -y pm-disable'
 alias dcc='drush cache-clear all'
 alias dsq='drush sql-cli'
+alias dsqlc='drush sql-connect'
 alias dsa='drush site-alias'
 alias dsaf='drush site-alias --full'
 alias dpr='drush user-password admin --password=admin'
+
+function dsqld() {
+  if [ -z "$1" ]
+  then
+    echo 'provide an output file'
+    return
+  else
+    drush sql-dump --result-file=${1}.sql --gzip
+  fi
+}
 
 # copied and modified from drush's own drush.complete.sh:
 # complete den, dis, dcd aliases with module names
@@ -33,24 +44,24 @@ complete -o nospace -F _drush_completion_grota ddi
 
 # cd to the passed parameter, using drush dd
 # parameter is autocompleted (see above) with module name
-alias dcd='_dcd'
-function _dcd() {
- s="$1"
-  if [ -z "$s" ]
-  then
-    builtin cd
-  else
-    d="$(drush drupal-directory $1 --local 2>/dev/null)"
-    if [ $? == 0 ]
-    then
-      echo "cd $d";
-      builtin cd "$d";
-    else
-      echo "Cannot cd to $s"
-    fi
-  fi
-}
-complete -o nospace -F _drush_completion_grota _dcd dcd
+#alias dcd='_dcd'
+#function _dcd() {
+# s="$1"
+#  if [ -z "$s" ]
+#  then
+#    builtin cd
+#  else
+#    d="$(drush drupal-directory $1 --local 2>/dev/null)"
+#    if [ $? == 0 ]
+#    then
+#      echo "cd $d";
+#      builtin cd "$d";
+#    else
+#      echo "Cannot cd to $s"
+#    fi
+#  fi
+#}
+#complete -o nospace -F _drush_completion_grota _dcd dcd
 
 # Find the drush executable and test it.
 d=$(which drush)
